//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3415.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3415.0.
// 
namespace ProductInfo.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductServiceSoap", Namespace="http://contentmaster.com/NorthwindServices")]
    public class ProductService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ProductService() {
            this.Url = "http://localhost/NorthwindServices/ProductService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://contentmaster.com/NorthwindServices/HowMuchWillItCost", RequestNamespace="http://contentmaster.com/NorthwindServices", ResponseNamespace="http://contentmaster.com/NorthwindServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Decimal HowMuchWillItCost(string productName, int howMany) {
            object[] results = this.Invoke("HowMuchWillItCost", new object[] {
                        productName,
                        howMany});
            return ((System.Decimal)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHowMuchWillItCost(string productName, int howMany, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HowMuchWillItCost", new object[] {
                        productName,
                        howMany}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Decimal EndHowMuchWillItCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Decimal)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://contentmaster.com/NorthwindServices/GetProductInfo", RequestNamespace="http://contentmaster.com/NorthwindServices", ResponseNamespace="http://contentmaster.com/NorthwindServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product GetProductInfo(string productName) {
            object[] results = this.Invoke("GetProductInfo", new object[] {
                        productName});
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProductInfo(string productName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProductInfo", new object[] {
                        productName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Product EndGetProductInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Product)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://contentmaster.com/NorthwindServices")]
    public class Product {
        
        /// <remarks/>
        public int ProductID;
        
        /// <remarks/>
        public string ProductName;
        
        /// <remarks/>
        public int SupplierID;
        
        /// <remarks/>
        public int CategoryID;
        
        /// <remarks/>
        public string QuantityPerUnit;
        
        /// <remarks/>
        public System.Decimal UnitPrice;
        
        /// <remarks/>
        public short UnitsInStock;
        
        /// <remarks/>
        public short UnitsOnOrder;
        
        /// <remarks/>
        public short ReorderLevel;
        
        /// <remarks/>
        public bool Discontinued;
    }
}
